log:
  show: True
  level: 30
program:
  start: "9:30"
  stop: "15:00"
trade:
  start: "9:30"
  stop: "15:00"
signals:
  exchange: BSE   # excel contain SR from this file
strategy:
  type: 2     # Delta Strategy
  base: BTC-DELTA
  stop_loss: 500
  target: 1000
  ttl: 60     # Time To Live in minutes for T1 buy trades
  quantity: 1
  slippage: 5
live: 1
broker: delta-india
