log:
  show: true
  level: 20
program:
  start: "9:15"
strategy_name: "Coinshort"
strategy:
  base: BTC-DELTA
  stop_loss: 150
  target: 150
  ttl: 15
  quantity: 1
  slippage: 0.5
  expiry_offset: 0
base_instrument:
  base: BTC
  diff: 100
  depth: 20
  exchange: DELTA
  instrument_token: 1001     # ws token for BTC-USD perpetual/future
  tradingsymbol: BTC-USD      # underlying future symbol
broker: delta-india
