log:
  show: True
  level: 10
program:
  start: "9:15"
  stop: "15:15"
trade:
  start: "9:30"
  stop: "15:00"
live: true
strategy:
  base: "BANKNIFTY"
  quantity: 150   # It is the total quantity, not the number of lots
  stop_loss: 60
  expiry_offset: 0       # 0 = current expiry, 1 = next expiry, 2 = next to next expiry
